/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.gerente;

import controller.renda_var.CadRendaVarController;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author B r u n o
 */
public class CadRendaVar extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadRendaFixa
     */
    public CadRendaVar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome_opTxt = new javax.swing.JTextField();
        tipo_opTxt = new javax.swing.JTextField();
        rendimentoTxt = new javax.swing.JTextField();
        cadVarBtn = new javax.swing.JButton();
        percentual_riscoTxt = new javax.swing.JSpinner();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar renda variável"));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        nome_opTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome da operação"));

        tipo_opTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de operação"));

        rendimentoTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Rendimento esperado"));

        cadVarBtn.setText("Cadastrar");
        cadVarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadVarBtnActionPerformed(evt);
            }
        });

        percentual_riscoTxt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        percentual_riscoTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Percentual de risco"));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nome_opTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(tipo_opTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(cadVarBtn)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rendimentoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(percentual_riscoTxt))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_opTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tipo_opTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(percentual_riscoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rendimentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadVarBtn)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        controller = new CadRendaVarController(this);
    }//GEN-LAST:event_formInternalFrameOpened

    private void cadVarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadVarBtnActionPerformed
        // TODO add your handling code here:
        if(getNome_opTxt().equals("") || getPercentual_riscoTxt() <= 0 ||
           getRendimentoTxt().equals("") || getTipo_opTxt().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para completar a ação");
        } else {
            controller.adicionaRendaFixa();
        }
    }//GEN-LAST:event_cadVarBtnActionPerformed

    public String getNome_opTxt() {
        return nome_opTxt.getText();
    }

    public int getPercentual_riscoTxt() {
        return (int) percentual_riscoTxt.getValue();
    }

    public String getRendimentoTxt() {
        return rendimentoTxt.getText();
    }

    public String getTipo_opTxt() {
        return tipo_opTxt.getText();
    }
    
    private CadRendaVarController controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadVarBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_opTxt;
    private javax.swing.JSpinner percentual_riscoTxt;
    private javax.swing.JTextField rendimentoTxt;
    private javax.swing.JTextField tipo_opTxt;
    // End of variables declaration//GEN-END:variables
}
