/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package view.gerente;

import controller.CadRendaFixaController;
import controller.RendaFixaController;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author B r u n o
 */
public class CadRendaFixa extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadRendaFixa
     */
    public CadRendaFixa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nome_opTxt = new javax.swing.JTextField();
        rendimentoTxt = new javax.swing.JTextField();
        prazoMinTxt = new javax.swing.JTextField();
        validadeTxt = new javax.swing.JTextField();
        cadFixaBtn = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar renda fixa"));
        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        nome_opTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Nome da operação"));

        rendimentoTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Taxa de rendimento"));

        prazoMinTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Prazo mínimo para resgate"));
        prazoMinTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prazoMinTxtActionPerformed(evt);
            }
        });

        validadeTxt.setBorder(javax.swing.BorderFactory.createTitledBorder("Validade da operação"));

        cadFixaBtn.setText("Cadastrar");
        cadFixaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadFixaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(nome_opTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(rendimentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(cadFixaBtn)))
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(validadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prazoMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_opTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rendimentoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(prazoMinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(validadeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cadFixaBtn)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prazoMinTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prazoMinTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prazoMinTxtActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        controller = new CadRendaFixaController(this);
    }//GEN-LAST:event_formInternalFrameOpened

    private void cadFixaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadFixaBtnActionPerformed
        // TODO add your handling code here:
        if(getNome_opTxt().equals("") || getPrazoMinTxt().equals("") ||
           getRendimentoTxt().equals("") || getValidadeTxt().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos para completar a ação");
        } else {
            controller.adicionaRendaFixa();
        }
    }//GEN-LAST:event_cadFixaBtnActionPerformed

    public String getNome_opTxt() {
        return nome_opTxt.getText();
    }

    public String getPrazoMinTxt() {
        return prazoMinTxt.getText();
    }

    public String getRendimentoTxt() {
        return rendimentoTxt.getText();
    }

    public String getValidadeTxt() {
        return validadeTxt.getText();
    }

    private CadRendaFixaController controller;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadFixaBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nome_opTxt;
    private javax.swing.JTextField prazoMinTxt;
    private javax.swing.JTextField rendimentoTxt;
    private javax.swing.JTextField validadeTxt;
    // End of variables declaration//GEN-END:variables
}
